

name: CI


on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2.1.2
      - uses: actions/checkout@v2
      - name: generate
        run: npm ci && npm run generate
